machine:
  pre:
    - mkfs -q /dev/ram1 1024
    - mkdir -p /share/USB1
    - mount /dev/ram1 /share/USB1
    - mkfs -q /dev/ram2 1024
    - mkdir -p /share/USB2
    - mount /dev/ram1 /share/USB2
  timezone:
    Asia/Jakarta
  node:
    version: 6.10.0
checkout:
dependencies:
  override:
    - npm install --dev
test:
  override:
    - npm run cover
  post:
    - bash <(curl -s https://codecov.io/bash)