language: node_js

sudo: required

dist: trusty

node_js:
  - stable

before_install:
  - sudo mkfs -q /dev/ram1 8192
  - sudo mkfs -q /dev/ram2 8192
  - sudo mkdir -p /share/USB1
  - sudo mkdir -p /share/USB2
  - sudo mount /dev/ram1 /share/USB1
  - sudo mount /dev/ram2 /share/USB2

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"