version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install --dev
      - run:
          name: Building .js and .d.ts file
          command: npm run build
      - run:
          name: Running tests
          command: npm run cover
      - run:
          name: Install codeclimate reporter
          command: npm install -g codeclimate-test-reporter
      - run:
          name: Upload test result to codeclimate
          command: codeclimate-test-reporter < coverage/lcov.info