jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install --dev
      - run:
          name: Running tests
          command: npm run cover
      - run:
          name: Upload test result to codecov
          command: bash <(curl -s https://codecov.io/bash)